# Generated by Django 4.1.7 on 2023-05-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Role ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Role Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID статуса')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название статуса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
            options={
                'db_table': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID задачи')),
                ('project_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('name', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание задачи')),
                ('is_on_kanban', models.BooleanField(default=True, verbose_name='Отображение на канбане')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Готовность задачи')),
                ('planned_start_date', models.DateField(verbose_name='Время начала задачи')),
                ('planned_finish_date', models.DateField(verbose_name='Время окончания задачи')),
                ('deadline', models.DateField(verbose_name='Жесткий дедлайн')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Время завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.task', verbose_name='Ссылка на родительскую задачу')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.status')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID подэтапа')),
                ('description', models.CharField(max_length=255, verbose_name='Описание этапа')),
                ('is_ready', models.BooleanField(default=False, verbose_name='Подэтап выполнен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.task')),
            ],
            options={
                'db_table': 'stages',
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID исполнителя')),
                ('user_id', models.IntegerField()),
                ('time_spent', models.TimeField(verbose_name='Время выполнения задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.role')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.task')),
            ],
            options={
                'db_table': 'executors',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID комментария')),
                ('user_id', models.IntegerField()),
                ('content', models.CharField(max_length=255, verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.task')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
