# Generated by Django 4.1.7 on 2023-03-22 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('task_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание задачи')),
                ('start_date', models.DateTimeField(verbose_name='Старт задачи')),
                ('finish_date', models.DateTimeField(verbose_name='Финиш задачи')),
                ('deadline', models.DateTimeField(verbose_name='Жесткий дедлайн')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланирована'), ('TO WORK', 'В работу'), ('IN WORK', 'В работе'), ('COMPLETED', 'Завершена')], max_length=20, verbose_name='Статус задачи')),
                ('executor', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='backend.user', verbose_name='Ответственный')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='owner_id', to='backend.user', verbose_name='Постановщик')),
            ],
        ),
    ]
