# Generated by Django 4.1.7 on 2023-06-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='time_spent',
            field=models.TimeField(blank=True, null=True, verbose_name='Время выполнения задачи'),
        ),
    ]
