# Generated by Django 4.1.7 on 2023-03-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='executor',
        ),
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ManyToManyField(default=None, null=True, to='backend.user', verbose_name='Ответственный'),
        ),
    ]
