# Generated by Django 4.1.7 on 2023-05-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_event', models.BigIntegerField()),
                ('title', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('id_director', models.BigIntegerField()),
                ('evaluation_criteria', models.BigIntegerField()),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'db_table': 'uralapi_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название команды')),
                ('id_tutor', models.BigIntegerField()),
                ('team_chat', models.URLField(blank=True, null=True, verbose_name='Ссылка на чат')),
                ('teg', models.CharField(max_length=200, unique=True, verbose_name='Тег')),
            ],
            options={
                'db_table': 'uralapi_team',
                'managed': False,
            },
        ),
    ]
