# Generated by Django 4.1.7 on 2023-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID комментария'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID исполнителя'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Role ID'),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID статуса'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID задачи'),
        ),
        migrations.AlterField(
            model_name='taskstage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID подэтапа'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.SmallAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
