# Generated by Django 4.1.7 on 2023-04-14 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_comment_id_alter_executor_id_alter_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Время завершения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Готовность задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_on_kanban',
            field=models.BooleanField(default=True, verbose_name='Отображение на канбане'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.task', verbose_name='Ссылка на родительскую задачу'),
        ),
    ]
