# Generated by Django 4.1.7 on 2023-03-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_task_executor_task_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID задачи'),
        ),
    ]
