# Generated by Django 4.1.7 on 2023-04-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstage',
            name='is_ready',
            field=models.BooleanField(verbose_name='Подэтап выполнен'),
        ),
    ]
